#baska bi ornek. file path fln emin degilim. sikko bi durum
version: "3.9"
services:
 todolist:
   build:
     context: .
     dockerfile: Dockerfile-CORRECTION
   ports:
   - "80:80"
 nginx:
   image: nginx
   depends_on:
   - todolist
   ports:
   - "81:80"

