# Stage 1
FROM node:10-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY angular-todo/package.json /app
RUN npm install
COPY angular-todo/ /app
RUN npm run build --prod

# Stage 2
FROM nginx:1.17.1-alpine as execution-step
COPY --from=build-step /app/dist /usr/share/nginx/html
