name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
## uses defines predefined github actions 
## checks out our repo to the container ubuntu machine runner. ls'li bi task yaratsan repoyu gorursun
#    - name: docker pull
#      run: |
#        docker pull harchoumi/todolist
    - name: run ls
      run: ls

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker logout
      run: docker logout

